SmallMarket-Project/frontend

src/components/navbar/myPagination.jsx

Add Pagination

---

.eslintrc.json
setup/pre-commit/pre-commit
setup/setup.md
src/components/UI/atoms/container/container.jsx
src/components/UI/atoms/container/style.js
src/components/UI/atoms/input/input.jsx
src/components/UI/atoms/input/style.js
src/components/UI/atoms/label/label.jsx
src/components/UI/atoms/label/style.js
src/components/UI/blocks/labeldInput/labeledInput.jsx
src/type/itemType.js
src/util/style/theme.js

```js
const Container = ({ width, display, children }) => {
return (
<StyledContainer width={width} display={display}>
{children}
</StyledContainer>
)
}
```
```js
const LabeledInput = ({ width, labelText, placeholder }) => {
return (
<Container width={width} display="block">
<Label labelText={labelText} />
<Input type="text" placeholder={placeholder} />
</Container>
)
}
```
-   Container 제작
-   LabeledInput 제작

Feat: LabeledInput, Container 제작 및 Input, Theme 수정

---

src/components/UI/atoms/grid/grid.jsx
src/components/UI/atoms/grid/style.js
src/util/style/theme.js

Feat: Grid Component 제작 및 Theme 추가

---

src/components/UI/atoms/link/link.jsx
src/components/UI/atoms/link/style.js

StyledLink를 작성하였습니다.
style.js
> 기본적으로 검은 글씨와 호버링했을때 볼드체가 되게 해두었습니다.
link,jsx
> parameter 설명
> children = <Link>Test</Link>에서 태그안의 내용을 가져옵니다.
> props = Link의 to 메서드에서 경로를 가져옵니다.
-   PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
-   혹은 급하게 PR을 merge해야하는 사유를 적어주세요.
(특이 사항 1)
우선은 링크의 목적상 URL을 넘기는 목적으로 사용한다고 생각되서 특별히 메서드를 만들지 않았습니다.
추후에 필요한 부분이 생기면 작업하겠습니다.
(시간)

StyledLink작성

---

src/components/UI/blocks/searchBar/searchBar.jsx
src/components/UI/container/header.jsx

searchBar 완성
searchBar 완성
특이사항 없
(시간)

searchBar 완성

---

src/app.jsx
src/components/UI/container/footer.jsx
src/components/UI/container/mainPage.jsx
src/components/router/customRouter.jsx
src/util/style/theme.js

- CustomRouter, Footer 추가 및 theme color 상세 구분 추가
- CustomRouter 추가
- App.jsx 구성 수정
- Theme colors 추가
- Footer 제작

Feat: CustomRouter, Footer 추가 및 theme color 상세 구분 추가

---

package-lock.json
package.json
rule/rule.md
src/components/UI/atoms/button/button.jsx
src/components/UI/atoms/button/style.js
src/components/UI/atoms/text/text.jsx
src/components/UI/blocks/card/card.jsx
src/components/UI/blocks/card/style.js
src/components/UI/blocks/searchBar/searchBar.jsx
src/components/UI/container/main.jsx
src/components/router/customRouter.jsx
src/index.js
src/store/actions/authAction.js
src/store/index.js
src/store/reducers/authReducer.js
src/store/reducers/index.js
src/util/style/theme.js
yarn.lock

-  Redux initial setting
- Card 개발
- store
- reducer init
- action init
- directory setting
- card setting
-   이상한 점 건의 바람

Feat: Redux initial setting. Card 개발

---

src/components/UI/atoms/link/style.js
src/components/UI/container/header.jsx

- header style fix
- header style fix

Fix: header style fix

---

src/components/UI/container/header.jsx
src/util/style/theme.js

theme에 header 추가
- Theme에 header theme 추가
- header에 theme css 적용

Fix: theme에 header 추가

---

src/components/UI/atoms/button/button.jsx
src/components/UI/atoms/button/style.js
src/components/UI/atoms/container/style.js
src/components/UI/atoms/grid/grid.jsx
src/components/UI/atoms/grid/style.js
src/components/UI/atoms/select/select.jsx
src/components/UI/atoms/select/syle.js
src/components/UI/blocks/info/infoCard.jsx
src/components/UI/blocks/info/infoHeader.jsx
src/components/UI/blocks/selectButton/selectButton.jsx
src/util/style/theme.js

- InfoHeader, InfoCard, SelectButton, Select 추가
- Button style 추가
- Select, Option 추가
- InfoHeader 추가
- InfoCard 추가
- SelectButton 추가

Feat: InfoHeader, InfoCard, SelectButton, Select 추가

---

src/components/UI/blocks/cartBar/cartBar.jsx
src/components/UI/blocks/cartBar/style.js

cartBar 추가 및 style 추가
- cartBar 추가
- cartBar에 대한 스타일링 추가

Add: cartBar 추가 및 style 추가

---

.eslintrc.json
.prettierrc

prettier 및 eslint 수정
ESLInt => end of Line 설정

settings : prettier 및 eslint 수정

---

craco.config.js
jsconfig.json
package-lock.json
package.json
src/components/UI/container/header.jsx
yarn.lock

craco 절대 경로 설정
craco 절대 경로 path 설정을 진행했습니다. 
```
src => @
components => @components
util => @util
type => @type
```
없습니다.
(시간)

settings : craco 절대 경로 설정

---

src/components/UI/atoms/button/style.js
src/components/UI/atoms/grid/style.js
src/components/UI/atoms/input/style.js
src/components/UI/atoms/label/style.js
src/components/UI/atoms/link/style.js
src/components/UI/atoms/select/select.jsx
src/components/UI/atoms/select/syle.js
src/components/UI/atoms/text/style.js
src/components/UI/atoms/text/text.jsx
src/components/UI/blocks/info/infoCard.jsx
src/components/UI/blocks/info/infoHeader.jsx
src/components/UI/blocks/searchBar/searchBar.jsx
src/components/UI/blocks/selectButton/selectButton.jsx
src/components/UI/container/adminContainer.jsx
src/components/UI/container/footer.jsx
src/components/UI/container/header.jsx

- AdminContainer 제작 및 atoms, blocks style 조정
- InfoHeader 제작
- InfoCard 제작
- AdminContainer 제작

Feat: AdminContainer 제작 및 atoms, blocks style 조정

---

src/components/UI/atoms/button/button.jsx
src/components/UI/blocks/labeledInput/labeledInput.jsx
src/components/UI/container/loginContainer.jsx
src/components/router/customRouter.jsx
src/util/style/theme.js

- LoginContainer 추가 및 Label type Button type 추가
- Theme font size 조정
- LoginContainer 제작
- Label type 추가
- Button type 추가

Feat: LoginContainer 추가 및 Label type Button type 추가

---

package-lock.json
package.json
src/components/UI/blocks/carousel/carousel.jsx
src/components/UI/blocks/carousel/style.js
src/components/router/customRouter.jsx
yarn.lock

Carousel제작, react-slick사용
(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부, 필수 아님 사진으로 대체 가능)
구현 내용 및 작업 했던 내역
1.Carousel추가
2.react-slick 사용
-   PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
-   혹은 급하게 PR을 merge해야하는 사유를 적어주세요.
(특이 사항 1)
(시간)

Carousel추가, react-slick추가

---

src/components/UI/atoms/input/input.jsx
src/components/UI/blocks/labeledInput/labeledInput.jsx
src/components/UI/blocks/modal/modal.jsx
src/components/UI/blocks/modal/style.js
src/components/UI/blocks/searchBar/searchBar.jsx
src/components/UI/container/NotFound.jsx
src/components/UI/container/loginContainer.jsx
src/components/router/customRouter.jsx
src/hooks/useForm.jsx
src/util/validation/validation.js

-  Modal, LoginContainer, alis 수정. Validation, NotFound page 추가

Fix: Modal, LoginContainer, alias 수정. Validation, NotFound page 추가

---

package-lock.json
package.json
src/components/UI/container/loginContainer.jsx
src/dev/data.js
src/storage/cookieStorage.js
src/store/actions/authAction.js
src/store/reducers/authReducer.js
src/store/reducers/index.js
src/store/types/userActionTypes.js
yarn.lock

- LoginContainer 및 auth redux 로직 수정.  user action types 추가. CookieStorage 추가.
- LoginContainer 로직 수정
- auth redux 로직 수정
- userActionTypes 추가
- CookieStorage 추가
-  훗날 사용할 react-beautiful-dnd node module 추가
- drag drop 구현 시 필요
- custom hook 으로 구현할 예정. 로직 구상중.

Fix: LoginContainer 및 auth redux 로직 수정.  user action types 추가

---

package-lock.json
package.json
src/components/UI/blocks/cart/cartBar.jsx
src/components/UI/blocks/cart/cartSidebar.jsx
src/components/UI/blocks/dragdrop/draggableBox.jsx
src/components/UI/blocks/dragdrop/droppableBox.jsx
src/components/UI/blocks/iconButton/iconButton.jsx
src/components/UI/blocks/modal/modal.jsx
src/components/UI/blocks/modal/style.js
src/components/UI/container/cartContainer.jsx
src/components/UI/container/loginContainer.jsx
src/components/UI/container/registerContainer.jsx
src/components/router/customRouter.jsx
yarn.lock

- RegisterContainer validation 추가 및 CartContanier drag drop 추가 및 cartItems, props 수정
- RegisterContainer validation 추가
- DraggableBox 추가
- DroppableBox 추가
- CartContainer drag drop 추가
- CartItems 수정
- CartSidebar props 수정

Fix: RegisterContainer validation 추가 및 CartContanier drag drop 추가 및 cartItems, props 수정

---

src/components/UI/blocks/detail/detailInfo.jsx
src/components/UI/container/detailContainer.jsx
src/components/router/customRouter.jsx

- DetailContainer 추가
- DetailInfo 추가

Add : detailInfo 추가, detailContainer 추가

---

src/components/UI/atoms/grid/grid.jsx
src/components/UI/atoms/grid/style.js
src/components/UI/blocks/card/card.jsx
src/components/UI/blocks/card/style.js
src/components/UI/blocks/carousel/style.js
src/components/UI/container/main.jsx
src/components/UI/container/productContainer.jsx
src/components/router/customRouter.jsx

- ProductContainer 추가 및 Atoms, Blocks style 수정
- ProductContainer 추가 및 Atoms, Blocks style 수정

Feat: ProductContainer 추가 및 Atoms, Blocks style 수정

---

src/components/UI/blocks/dropdown/dropdownList.jsx
src/components/UI/container/header.jsx

Add : DropdownList

---

src/components/UI/container/myPageContainer.jsx
src/service/authService.js

- myPageSeller 주석
- authService 판매자 구분 컬렉션

Fix : myPageSeller 부분 주석처리 & authService 판매자 구분 컬렉션 만들기

---

src/components/UI/container/cartContainer.jsx
src/components/UI/container/loginContainer.jsx
src/components/UI/container/registerContainer.jsx
src/service/authService.js

Fix: Login, Register 개선 및 CartContainer 오류 수정

---

src/components/UI/blocks/cart/cartBar.jsx
src/components/UI/container/cartContainer.jsx
src/components/UI/container/detailContainer.jsx
src/components/UI/container/header.jsx
src/service/authService.js
src/service/cartService.js
src/service/productService.js
src/type/foodItemType.js

- CartService delete, add, get 추가

Feat: CartService delete, add, get 추가

---

src/components/UI/blocks/card/card.jsx
src/components/UI/blocks/cart/cartBar.jsx
src/components/UI/container/cartContainer.jsx
src/components/UI/container/detailContainer.jsx
src/components/UI/container/productContainer.jsx
src/service/cartService.js
src/service/productService.js

- Cart quantity change 추가
- CartService quantity change 추가
- ProductService get by id 함수 추가
- CartContainer 전체 가격 수정

Fix: Cart quantity change 추가

---

src/components/UI/atoms/select/select.jsx
src/components/UI/blocks/paginate/paginate.jsx
src/components/UI/container/productContainer.jsx
src/hooks/usePaginate.jsx

Paginate 추가
(작업 내역 확인하기 편하도록 gif 첨부, 필수 아님 사진으로 대체 가능)
구현 내용 및 작업 했던 내역
select -> 기본 옵션추가
paginate추가
productContainer -> pagination기능 추가
-   PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
-   혹은 급하게 PR을 merge해야하는 사유를 적어주세요.
(특이 사항 1)
(시간)

Paginate 추가

---

src/components/UI/blocks/carousel/carousel.jsx
src/components/UI/blocks/cart/cartSidebar.jsx
src/components/UI/blocks/info/infoCard.jsx
src/components/UI/blocks/info/infoHeader.jsx
src/components/UI/blocks/payment/paymentDetail.jsx
src/components/UI/blocks/payment/paymentInfo.jsx
src/components/UI/container/adminContainer.jsx
src/components/UI/container/cartContainer.jsx
src/components/UI/container/myPageContainer.jsx
src/components/UI/container/paymentContainer.jsx
src/components/UI/container/productContainer.jsx
src/icon/icon.jsx
src/service/authService.js

- MyPage, Payment Page, Product fix

Fix: MyPage, Payment Page, Product fix

---

src/components/UI/blocks/card/card.jsx
src/components/UI/blocks/card/style.js
src/components/UI/blocks/paginate/paginate.jsx
src/components/UI/container/productContainer.jsx
src/components/router/customRouter.jsx
src/service/productService.js

- productsContainer 수정
- produtcsService allItems 추가
- cardStyle 이미지 사이즈 조절
- 잘못된 함수이름 수정

productsAllItems 추가 및 cardImgSize 조절

---

package-lock.json
package.json
src/components/UI/blocks/payment/paymentDetail.jsx
src/components/UI/blocks/payment/paymentInfo.jsx
src/components/UI/container/loginContainer.jsx
src/components/UI/container/myPageContainer.jsx
src/components/UI/container/paymentContainer.jsx
src/service/authService.js
src/service/payService.js
src/util/validation/validation.js
yarn.lock

- PaymentService, kakaopay, payment validation, add axios
- PaymentService
- kakaopay
- payment validation
-add axios

Feat: PaymentService, kakaopay, payment validation, add axios

---

src/components/UI/blocks/card/card.jsx
src/components/UI/blocks/card/style.js
src/components/UI/container/myPageContainer.jsx
src/service/authService.js

- cardStyle 수정
- authService 회원탈퇴 로그인 막기

cardStyle 수정, authService 회원탈퇴

---

src/components/UI/blocks/mypage/myPageMenuBar.jsx
src/components/UI/blocks/mypage/myPageProfile.jsx
src/components/UI/blocks/mypage/myPageSellerOrderList.jsx
src/components/UI/blocks/mypage/myPageSidebar.jsx
src/components/UI/container/header.jsx
src/components/UI/container/myPageContainer.jsx
src/service/authService.js
src/service/payService.js
src/service/productService.js

- Mypage sale & seller Get Info
- MypageMenubar UI
- MypageOrderlist UI
- MypageProfile Edit username
- MypageContainer
- AuthService Edit username
- PayService Get sale Info
- ProductsService Get seller Info

Mypage seller & sale list Get Information and Create UI Container, Mypage Profile Edit username

---

src/components/UI/blocks/info/infoCard.jsx
src/components/UI/container/adminContainer.jsx
src/service/authService.js

- authService User block
-authContainer User block logic

Fix: authService Admin이 사용자 블락기능 추가

---

src/components/UI/blocks/info/infoCard.jsx
src/components/UI/container/adminContainer.jsx

- AdminContainer user detail modal

Fix: AdminContainer user detail modal
